# Site settings
title: Gregory Vekemans
email: gregory.vekemans@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance web designer and developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site

twitter_username: GregoryVekemans
github_username:  gregoryVK
exclude: [node_modules, npm-debug.log, package.json]
permalink: /:categories/:title

links:

  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles

# Build settings
markdown: kramdown
